version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - node/test:
        context: project-catwalk
jobs:
  node/test:
    steps:
      - checkout
      - run:
          name: "echo AUTHORIZATION that is part of our context"
          command: |
            echo $AUTHORIZATION
